export enum RoutingConstants {
  AUTHORIZATION = 'authorization',
  MAIN = '',
  EMPLOYEES = 'employees',
  PROJECTS = 'projects',
  LOGIN = 'login',
  REGISTRATION = 'registration',
  CREATE = 'create',
  UPDATE = 'update',
  INFO = 'info',
  ENTITY = 'entity',
  ROLES = 'roles',
  CATEGORIES = 'categories',
  PROJECT_ROLES = 'project-roles',
  SPECIALIZATION = 'specializations',
  SKILLS = 'skills',
  LEVELS = 'levels',
  RESPONSIBILITIES = 'responsibilities',
  LANGUAGES = 'languages',
}
